# Generated by Django 3.1.7 on 2021-04-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_type_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_food',
            field=models.CharField(choices=[('Irani', 'ایرانی'), ('fastfood', 'فست فود'), ('deser', 'دسر'), ('drink', 'نوشیدنی')], default='irani', max_length=100, verbose_name='نوع غذا'),
        ),
    ]
