# Generated by Django 3.1.7 on 2021-04-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210408_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_food',
            field=models.CharField(choices=[('drinks', 'ایرانی'), ('Ff', 'فست فود'), ('De', 'دسر'), ('Dr', 'نوشیدنی')], default='Ir', max_length=100, verbose_name='نوع غذا'),
        ),
    ]
